name: Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      RP_TOKEN: ${{ secrets.RP_TOKEN }}

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i && npx playwright install chromium
    - run: npm test
